### ISSUE TITLE
Doesn't work in Python 3.8

### ISSUE THREAD

**Issue by kr3go6** [James-Ansley/cowsay#1]
Using built-in collection types (such as dict or list) as generic in type hints is only available since Python 3.9, so the following line will raise an error:

```
def read_dot_cow(f: TextIO, escapes: dict[str, str]=None) -> str:
TypeError: 'type' object is not subscriptable
```

You should probably change the required Python version in "setup.py" to ">=3.9"

**Comment by James-Ansley** [comment]
Thanks for this!
I have released a patch that has the correct python version.
